### ISSUE TITLE
No such file or directory while add patch in linux kerenl

### ISSUE THREAD

**Issue by PratikGajera** [kopasiak/f_dl_ffs#3]
I am follow below sequence.

first download patch file from available github https://github.com/kopasiak/f_dl_ffs/ link.

Try to add command line on add patch file.

$patch < 0001-f_fs-accept-unknown-ep-descriptors.patch 

then after get 

can't find file to patch at input line 15
Perhaps you should have used the -p or --strip option?
## The text leading up to this was:

|From 884b6752010bb39a311d7abdd62109f00fae1ef9 Mon Sep 17 00:00:00 2001
|From: Igor Kotrasinski i.kotrasinsk@samsung.com
|Date: Thu, 27 Aug 2015 15:46:26 +0200
|Subject: [PATCH 1/4] f_fs: accept unknown ep descriptors
|
|Signed-off-by: Igor Kotrasinski i.kotrasinsk@samsung.com
|---
| drivers/usb/gadget/function/f_fs.c | 2 +-
| 1 file changed, 1 insertion(+), 1 deletion(-)
|
|diff --git a/drivers/usb/gadget/function/f_fs.c b/drivers/usb/gadget/function/f_fs.c
|index 6e7be91..aadf613 100644
|--- a/drivers/usb/gadget/function/f_fs.c
## |+++ b/drivers/usb/gadget/function/f_fs.c

File to patch: 

And i confused which File to patch apply and f_fs.c is not available in my linux system for given path.
So how can f_fs.c file add to your recommended path.

**Comment by kopasiak** [comment]
use git am in root directory of kernel source
